version: 2
# Config Docs: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file

updates:
  # JAVASCRIPT package.json updates

  - directory: "/client-admin"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ğŸ”© p:client-admin"]

  - directory: "/file-server"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]

  ## Disabled (until major manual update)

  - directory: "/server"
    package-ecosystem: "npm"
    labels: ["dependencies", "ğŸ”© p:server"]
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - directory: "/client-participation"
    package-ecosystem: "npm"
    labels: ["dependencies", "ğŸ”© p:client-participation"]
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  - directory: "/client-report"
    package-ecosystem: "npm"
    labels: ["dependencies", "ğŸ”© p:client-report"]
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"

  # DOCKER image updates

  - directory: "/math"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure", "ğŸ”© p:math"]
    schedule:
      interval: "weekly"

  - directory: "/server"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure", "ğŸ”© p:server"]
    schedule:
      interval: "weekly"

  - directory: "/file-server"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure"]
    schedule:
      interval: "weekly"

  - directory: "/client-admin"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure", "ğŸ”© p:client-admin"]
    schedule:
      interval: "weekly"

  - directory: "/client-participation"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure", "ğŸ”© p:client-participation"]
    schedule:
      interval: "weekly"

  - directory: "/client-report"
    package-ecosystem: "docker"
    labels: ["dependencies", "âš’ï¸ infrastructure", "ğŸ”© p:client-report"]
    schedule:
      interval: "weekly"

  # GITHUB ACTIONS external action updates

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    labels: ["dependencies", "âš’ï¸ infrastructure"]
    schedule:
      interval: "daily"
