apiVersion: v1
kind: ConfigMap
metadata:
  name: polis-server
data:
  # For admin functionality, fill this out
  ADMIN_EMAILS: "[]"
  ADMIN_EMAIL_DATA_EXPORT: ""
  ADMIN_EMAIL_DATA_EXPORT_TEST: ""
  ADMIN_EMAIL_EMAIL_TEST: ""
  ADMIN_UIDS: "[]"

  DATABASE_FOR_READS_NAME: DATABASE_URL
  DATABASE_URL: postgres://postgres:oiPorg3Nrz0yqDLE@postgres:5432/polis-dev

  # These may be the deprecated settings for submitting web requests to the math worker
  WEBSERVER_USERNAME: ws-user
  WEBSERVER_PASS: ws-pass

  # Set to `false` for production
  DEV_MODE: "true"

  # Set the domain name; make sure this matches what"s running on math node
  DOMAIN_OVERRIDE: polis.local

  # Options: prod, preprod, dev
  MATH_ENV: dev
  PORT: "5000"

  # Set to `true` and insert google creds if desired
  SHOULD_USE_TRANSLATION_API: "false"
  # GOOGLE_CREDENTIALS_BASE64: ...
  # GOOGLE_CREDS_STRINGIFIED: ...

  # These need to be configured to point to the local file server
  STATIC_FILES_HOST: polis-file-server
  STATIC_FILES_ADMINDASH_PORT: "80"
  STATIC_FILES_PORT: "80"

  AWS_REGION: us-east-1

  # Options: maildev, aws-ses, mailgun
  EMAIL_TRANSPORT_TYPES: maildev
  POLIS_FROM_ADDRESS: "Example <team@example.com>"

  # These pieces of functionality will likely be removed in the near future
  DISABLE_INTERCOM: "true"
  STRIPE_SECRET_KEY: sk_test_NFBDEThkpHCYBzXPJuBlY8TW

  # Note(geoah): This seems to be needed until the following TODO is resolved:
  # https://github.com/compdemocracy/polis/blob/9a294140bbfc50d5bbb50ce4e474f4ad72541881/server/src/session.ts#L8-L10
  ENCRYPTION_PASSWORD_00001: "PLEASE-CHANGE-ME"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polis-server
spec:
  selector:
    matchLabels:
      app: polis-server
  template:
    metadata:
      labels:
        app: polis-server
    spec:
      containers:
        - image: docker.io/compdem/polis-server:dev
          name: polis-server
          envFrom:
          - configMapRef:
              name: polis-server
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: polis-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: polis-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polis-server
spec:
  rules:
    - host: polis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: polis-server
                port:
                  number: 80


