on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - edge
      - stable

  paths:
    - .github/workflows/deploy-preprod.yml
    - client-admin
    - client-participation
    - client-report


jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.3.4

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      #- uses: DeLaGuardo/setup-clojure@3.2
        #with:
          #tools-deps: 1.10.1
          #cli:  1.10.1.693
          #lein: 2.9.4

      - name: Build
        # Runs all except integration tests which require database and setup/teardown
        run: ./bin/build-static-assets.clj

      #- name: Push
        ## Runs all except integration tests which require database and setup/teardown
        #run: ./bin/deploy-static-assets.clj

