name: Test Math

on:
  push:
    branches: ["dev", "504-clj-tests"]
    # Note: Only configured for client-admin right now.
    paths:
      - .github/workflows/test-clojure.yml
      - math/**
  pull_request:
    types: ["opened", "reopened", "synchronize"]
    paths:
      - .github/workflows/test-clojure.yml
      - math/**

jobs:
  test-clj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Prepare java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Install Clojure tooling
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.693

      - name: Run Clojure tests
        working-directory: math
        # Runs all except integration tests which require database and setup/teardown
        run: "clojure -M:test"
